### ISSUE TITLE
mathematically-wrong fix

### ISSUE THREAD

**Issue by dosten** [spotify/phpconf-argentina-2014#1]
Removing the solution...

**Comment by yuriteixeira** [comment]
Beautiful! Thanks for your time man! I am here at the room A, on the mercado libre talk. Would like a lot to give you your gift and chat with you a little bit :smile:

**Comment by dosten** [comment]
I'm here too :)

**Comment by yuriteixeira** [comment]
Ok, I'm with a Spotify shirt in the middle of the room :)

**Comment by yuriteixeira** [comment]
Couldn't find you :-( pls, ping me on twitter @yuriteixeira

**Comment by yuriteixeira** [comment]
And I will remove your answer, just to don't reveal it to the others :)
